title: [MATURITNÉ TÉMY - HTA, DEH, NKO]
description: [Vypracované témy]
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-titles-from-headings
- jekyll-relative-links
- jekyll-spaceship
markdown: GFM
